import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {UserProvider} from "@auth0/nextjs-auth0/client";
import {ApolloProvider} from "@apollo/client";

import {apolloClient} from "./lib/apollo";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <UserProvider>
      <ApolloProvider client={apolloClient}>
        <html lang="en">
        <body className={inter.className}>{children}</body>
        </html>
      </ApolloProvider>
    </UserProvider>
  )
}
