import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {UserProvider} from "@auth0/nextjs-auth0/client";
import {__DEV__} from "@apollo/client/utilities/globals";
import {loadDevMessages, loadErrorMessages} from "@apollo/client/dev";
import {PageLayout} from "@/app/components/PageLayout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

if (__DEV__) {  // Adds messages only in a dev environment
  loadDevMessages();
  loadErrorMessages();
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <UserProvider>
      <body className={inter.className}>
      <PageLayout>{children}</PageLayout></body>
    </UserProvider>
    </html>
  )
}
